#!/usr/bin/env node
/* eslint-disable no-console */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
function readJsonIfExists(filePath){if(!fs.existsSync(filePath))return null;try{return JSON.parse(fs.readFileSync(filePath,'utf8'));}catch(e){console.warn(`[recover:cms] Skipped unreadable JSON: ${filePath} (${e.message})`);return null;}}
function extractArrayFromTsLiteral(filePath, exportName){if(!fs.existsSync(filePath))return [];const src=fs.readFileSync(filePath,'utf8');const marker=`export const ${exportName}`;const start=src.indexOf(marker);if(start===-1)return [];const eq=src.indexOf('=',start);const arrStart=src.indexOf('[',eq);if(eq===-1||arrStart===-1)return [];let depth=0,end=-1;for(let i=arrStart;i<src.length;i++){const ch=src[i];if(ch==='[')depth++;if(ch===']'){depth--;if(depth===0){end=i;break;}}}if(end===-1)return [];const literal=src.slice(arrStart,end+1);try{return Function(`"use strict"; return (${literal});`)();}catch(e){console.warn(`[recover:cms] Failed to parse ${filePath} export ${exportName}: ${e.message}`);return [];}}
function deepMergeMissing(target,source){if(!source||typeof source!=='object'||Array.isArray(source))return target;const out=target&&typeof target==='object'&&!Array.isArray(target)?{...target}:{};for(const [k,v] of Object.entries(source)){if(out[k]===undefined||out[k]===null||out[k]===''){out[k]=v;continue;}if(v&&typeof v==='object'&&!Array.isArray(v)&&out[k]&&typeof out[k]==='object'&&!Array.isArray(out[k]))out[k]=deepMergeMissing(out[k],v);}return out;}
function mergeByIdentity(current,recovered,keyName){const res=[...current];const idx=new Map();for(let i=0;i<res.length;i++){const it=res[i];const key=it?.[keyName]||it?.slug||it?.id;if(key)idx.set(String(key),i);}let restored=0,dupes=0;for(const it of recovered){if(!it||typeof it!=='object')continue;const key=it?.[keyName]||it?.slug||it?.id;if(!key)continue;const mk=String(key);if(!idx.has(mk)){res.push(it);idx.set(mk,res.length-1);restored++;}else{const i=idx.get(mk);const m=deepMergeMissing(res[i],it);if(JSON.stringify(m)!==JSON.stringify(res[i]))res[i]=m;else dupes++;}}return {items:res,restored,dupes};}
async function run(){const apiContentPath=path.join(root,'server','data','content.json');const legacyServerContentPath=path.resolve(root,'..','server','data','content.json');const snapshots=[readJsonIfExists(apiContentPath),readJsonIfExists(legacyServerContentPath),readJsonIfExists(path.join(root,'server','data','backup-content.json'))].filter(Boolean);const recovered={projects:[],services:[],blogPosts:[],mediaFiles:[],pageContent:{},settings:{}};for(const s of snapshots){recovered.projects.push(...(s.projects||[]));recovered.services.push(...(s.services||[]));recovered.blogPosts.push(...(s.blogPosts||[]));recovered.mediaFiles.push(...(s.mediaFiles||[]));recovered.pageContent=deepMergeMissing(recovered.pageContent,s.pageContent||{});recovered.settings=deepMergeMissing(recovered.settings,s.settings||{});}recovered.projects.push(...extractArrayFromTsLiteral(path.resolve(root,'..','cms/apps/cms/src/data/projects.ts'),'projects'));recovered.services.push(...extractArrayFromTsLiteral(path.resolve(root,'..','cms/apps/cms/src/data/services.ts'),'services'));recovered.blogPosts.push(...extractArrayFromTsLiteral(path.resolve(root,'..','cms/apps/cms/src/data/blogSeed.ts'),'defaultBlogPosts'));const before=readJsonIfExists(apiContentPath)||{};const current={...before};const p=mergeByIdentity(current.projects||[],recovered.projects,'slug');current.projects=p.items;const s=mergeByIdentity(current.services||[],recovered.services,'slug');current.services=s.items;const b=mergeByIdentity(current.blogPosts||[],recovered.blogPosts,'slug');current.blogPosts=b.items;const m=mergeByIdentity(current.mediaFiles||[],recovered.mediaFiles,'id');current.mediaFiles=m.items;current.pageContent=deepMergeMissing(current.pageContent||{},recovered.pageContent||{});current.settings=deepMergeMissing(current.settings||{},recovered.settings||{});const report={projectsFound:recovered.projects.length,projectsRestored:p.restored,servicesFound:recovered.services.length,servicesRestored:s.restored,articlesFound:recovered.blogPosts.length,articlesRestored:b.restored,mediaFound:recovered.mediaFiles.length,mediaRestored:m.restored,skippedDuplicates:p.dupes+s.dupes+b.dupes+m.dupes,unresolvedMediaRefs:0};const mediaIds=new Set((current.mediaFiles||[]).map(x=>x?.id).filter(Boolean));for(const arr of [current.projects||[],current.blogPosts||[]])for(const item of arr)for(const f of ['featuredImage','mainImage','coverImage','heroImage']){const v=item?.[f];if(typeof v==='string'&&v.startsWith('media://')&&!mediaIds.has(v.slice(8)))report.unresolvedMediaRefs++;}current.recoveryLog=[...(current.recoveryLog||[]),{ranAt:new Date().toISOString(),report}];fs.writeFileSync(apiContentPath,`${JSON.stringify(current,null,2)}\n`);console.log('=== CMS Recovery Report ===');console.log(JSON.stringify(report,null,2));console.log(`Updated content store: ${apiContentPath}`);}run().catch((e)=>{console.error('[recover:cms] Failed:',e);process.exit(1);});
